### ISSUE TITLE
Users can authenticate

### ISSUE THREAD

**Issue by kabaros** [CodeYourFuture/orula#53] opened 2018-08-13 11:07 UTC
**As a** Student or Mentor
**I want to** be able to authenticate with a username and password
**So that I** can see only the bits of the application I am interested in and view/edit my personal information

[ ] Use `PassportJS` to protect the Node endpoint
[ ] Add a React Component to authenticate
[ ] Add a protected route that only shows when you're authenticated

- Use PassportJS - http://www.passportjs.org/docs/
- https://mherman.org/blog/2016/09/25/node-passport-and-postgres/

**TC03**  : Test For Front End Authentication
Preconditions/General requirements :
1 . Registered users must log in with a valid email address and password.
Test Steps :	
1.	In the home page, navigate to the menu option of interest or choice. For example “personal information”.
Expected Result:  Personal information page should be displayed where the user can view his / her personal details.

**Comment by okolochuks** [comment] 2018-08-20 17:35
I tested the acceptance criteria in heroku and i discovered : 
1; There's no option where users can put in there details - log in .
So in conclusion there should be a menu to allow users to log in in order  to effectively test the acceptance criteria and hence the issue is not closed yet.

**Comment by NateWr** [comment] 2018-08-20 17:39
^ @islam95 can you check this on the heroku deployment? Are your changes fully in place there?

**Comment by islam95** [comment] 2018-08-20 18:14
Nate and Austine, I tested it locally and it works perfectly. Also, Loic checked it in his machine and he liked it. So I think it’s the pronlem with Heroku deployment of the project. As soon as it is fixed by Daniel you will be able to fully test my code or after merging it to dev.

**Comment by islam95** [comment] 2018-08-20 18:17
However, I saw the login page in Heroku deployment when you can put you credentials in order to login. Not sure why Austine did not see that.

**Comment by islam95** [comment] 2018-08-22 11:39
Login credentials: 
email: islam@email.com
password: islam123

**Comment by okolochuks** [comment] 2018-08-23 12:48
Hi  folks having sorted the challenges QA/QC's is having conducting their tests, we hereby certify that all necessary requirements and acceptance criteria for user's login authentication has all been met and therefore close the issue.

**Closed** 2018-08-23 12:49 UTC
Labels: review wanted
